apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spot-fleet-tagger
  name: spot-fleet-tagger
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: spot-fleet-tagger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: youriamrolehere # https://github.com/jtblin/kube2iam
        prometheus_io_port: "8080"
        prometheus_io_scrape: "true"
      labels:
        app: spot-fleet-tagger
    spec:
      containers:
      - name: tagger
        env:
        - name: SPOT_FLEET_REQUEST_IDS
          value: "sfr-xxxx-xxxx,sfr-yyyy-yyyy"
        - name: TAGS
          value: "Owner:user@domain,Cluster:us-west-2"
        image: your.private.registry:8443/spot-fleet-tagger
        ports:
        - containerPort: 8000
          protocol: TCP

